#!/usr/bin/env python3
"""Task row M6-03: soak, load, chaos and fairness experiments against a local
relay and synthetic devices, driven through the shipped binaries.

    scripts/m6-soak.py soak     --bin-dir DIR --logs DIR [--duration 7200]
    scripts/m6-soak.py load     --bin-dir DIR --logs DIR
    scripts/m6-soak.py chaos    --bin-dir DIR --logs DIR
    scripts/m6-soak.py fairness --bin-dir DIR --logs DIR
    scripts/m6-soak.py summarize --logs DIR --run RUN_DIR

Every experiment brings up its own stack from an empty Redis namespace with
the same shipped commands the operator guide uses (`credentials create`,
`credentials import`, `activate-first-incarnation`, `provision-catalog`,
`add-user`, `add-device`, `add-service`, `set-grant`, `serve`, `connect`).
Every consumer request goes device -> relay -> consumer over real TLS
sockets; nothing bypasses the relay.

Redis: `soak`, `load` and `fairness` use the shared plaintext Redis
(`--redis`, default 127.0.0.1:63790) under a unique namespace, fronted by a
TLS forwarder child process, and delete the namespace on exit.  `chaos`
starts its OWN throwaway `redis:8.4.0-alpine` container (named
`m6-03-soak-chaos-<nonce>`), because it pauses Redis; it never pauses,
restarts or reads another container, and removes its container on exit.

Output: one run directory per invocation under `--logs`, holding
`requests.csv` (one row per consumer request: wall time, kind, worker,
latency, HTTP status, error code, execution class, integrity), `samples.csv`
(RSS and open file descriptors of the relay, devices and forwarder, and the
relay's metrics gauges, over time), `events.jsonl` (faults, phases, device
sessions and rotations) and `summary.json`.  The first line of every log
carries the run nonce and `head=<sha>`.

Synthetic data only: payloads are generated bytes, tokens are signed by a
throwaway issuer key and never written to a log.
"""

from __future__ import annotations

import argparse
import asyncio
import base64
import csv
import json
import os
import re
import signal
import socket
import ssl
import statistics
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ISSUER = "https://issuer.m6-03-soak.invalid/"
AUDIENCE = "agent-tunnel"
CANARY = b"m1-device-a-synthetic"
MCP_PROFILE = "mcp-2025-11-25"
REDIS_IMAGE = ("redis:8.4.0-alpine@sha256:"
               "6cbef353e480a8a6e7f10ec545f13d7d3fa85a212cdcc5ffaf5a1c818b9d3798")


# ---------------------------------------------------------------- utilities

def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z")


def head_sha() -> str:
    try:
        return subprocess.run(["git", "-C", str(REPO), "rev-parse", "HEAD"], capture_output=True,
                              text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def run(args: list[str], cwd: Path | None = None, stdin: bytes | None = None,
        check: bool = True, timeout: float = 120) -> subprocess.CompletedProcess:
    completed = subprocess.run([str(a) for a in args], cwd=str(cwd) if cwd else None,
                               input=stdin, capture_output=True, timeout=timeout, check=False)
    if check and completed.returncode != 0:
        raise SystemExit(f"step failed ({completed.returncode}): {' '.join(map(str, args[:3]))}: "
                         f"{completed.stderr.decode(errors='replace')[-800:]}")
    return completed


def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def set_key(document: str, key: str, value: str) -> str:
    pattern = re.compile(rf"^{re.escape(key)} = .*$", re.M)
    if not pattern.search(document):
        raise SystemExit(f"example has no `{key} =` line")
    return pattern.sub(lambda _: f"{key} = {value}", document, count=1)


def tq(path: Path | str) -> str:
    return json.dumps(str(path))


def resp(host: str, port: int, parts: list[str]) -> bytes:
    request = f"*{len(parts)}\r\n".encode()
    for part in parts:
        data = part.encode()
        request += f"${len(data)}\r\n".encode() + data + b"\r\n"
    with socket.create_connection((host, port), timeout=10) as sock:
        sock.sendall(request)
        sock.shutdown(socket.SHUT_WR)
        reply = b""
        while True:
            chunk = sock.recv(65536)
            if not chunk:
                return reply
            reply += chunk


def delete_namespace(host: str, port: int, namespace: str) -> int:
    prefix = f"tunnel-catalog:{namespace}:"
    cursor, total = "0", 0
    while True:
        text = resp(host, port, ["SCAN", cursor, "MATCH", f"{prefix}*", "COUNT", "1000"]).decode(
            errors="replace")
        lines = text.split("\r\n")
        cursor = lines[2] if len(lines) > 2 else "0"
        keys = [line for line in lines if line.startswith(prefix)]
        if keys:
            resp(host, port, ["DEL", *keys])
            total += len(keys)
        if cursor == "0":
            return total


def percentile(values: list[float], pct: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    index = min(len(ordered) - 1, max(0, int(round(pct / 100.0 * len(ordered) + 0.5)) - 1))
    return ordered[index]


# ------------------------------------------------------ child processes

def _child_setup() -> None:
    """Runs in each child before exec: on Linux, ask for SIGTERM when the
    harness dies (the parent-death signal survives exec).  Children are also
    started in their own session (process group), which `stop_group` kills."""
    if sys.platform.startswith("linux"):
        try:
            import ctypes
            ctypes.CDLL("libc.so.6", use_errno=True).prctl(1, signal.SIGTERM)  # PR_SET_PDEATHSIG
        except OSError:
            pass


def spawn(args: list[str], **kwargs) -> subprocess.Popen:
    """Start a harness child in its own process group.  Call only from the
    main thread: the Linux parent-death signal follows the spawning thread."""
    assert threading.current_thread() is threading.main_thread(), "spawn from the main thread"
    return subprocess.Popen(args, start_new_session=True, preexec_fn=_child_setup, **kwargs)


def stop_group(proc: subprocess.Popen | None, timeout: float = 15) -> None:
    """SIGTERM the child's whole process group, then SIGKILL it if it lingers."""
    if proc is None:
        return
    try:
        os.killpg(proc.pid, signal.SIGCONT)
        os.killpg(proc.pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        pass
    try:
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        pass
    try:
        os.killpg(proc.pid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError):
        pass
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        pass


# ------------------------------------------------------- the TLS forwarder

async def _pump(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
    try:
        while True:
            data = await reader.read(65536)
            if not data:
                break
            writer.write(data)
            await writer.drain()
    except (OSError, asyncio.IncompleteReadError, ssl.SSLError):
        pass
    finally:
        try:
            writer.close()
        except OSError:
            pass


def forwarder_main(args: argparse.Namespace) -> None:
    """A TLS listener in front of a plaintext Redis, so `rediss://` works."""
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(args.cert, args.key)
    upstream_host, upstream_port = args.upstream.rsplit(":", 1)

    async def handle(reader, writer):
        try:
            up_reader, up_writer = await asyncio.open_connection(upstream_host, int(upstream_port))
        except OSError:
            writer.close()
            return
        await asyncio.gather(_pump(reader, up_writer), _pump(up_reader, writer))

    async def main():
        # The relay dials `localhost`, which may resolve to ::1 first; listen
        # on both loopback families where the host has them.
        hosts = ["127.0.0.1"]
        if socket.has_ipv6:
            try:
                with socket.socket(socket.AF_INET6) as probe:
                    probe.bind(("::1", 0))
                hosts.append("::1")
            except OSError:
                pass
        server = await asyncio.start_server(handle, hosts, args.port, ssl=context)
        print(f"forwarder listening port={args.port}", flush=True)
        async with server:
            await server.serve_forever()

    asyncio.run(main())


# --------------------------------------------------------------- the stack

class Stack:
    """One relay, its Redis TLS forwarder and its synthetic devices."""

    def __init__(self, bins: Path, run_dir: Path, redis: tuple[str, int], tag: str,
                 nonce: str, rotation: tuple[int, int, int] = (300, 10, 30),
                 relay_extra: str = ""):
        self.bins = bins
        self.run_dir = run_dir
        self.work = run_dir / "work"
        self.work.mkdir(parents=True, exist_ok=True)
        self.redis = redis
        self.nonce = nonce
        self.namespace = f"{tag}-{nonce}"
        self.rotation = rotation
        self.relay_extra = relay_extra
        self.relay: subprocess.Popen | None = None
        self.relay_procs: list[subprocess.Popen] = []
        self.forwarder: subprocess.Popen | None = None
        self.devices: dict[str, dict] = {}
        self.users: dict[str, dict] = {}
        self.relay_starts = 0
        self.events = (run_dir / "events.jsonl").open("a", buffering=1)
        self.tokens: dict[tuple[str, str], tuple[float, str]] = {}
        self.token_lock = threading.Lock()

    # -- events
    def event(self, name: str, /, **fields) -> None:
        record = {"t": round(time.time(), 3), "at": now_iso(), "event": name,
                  "load1": round(os.getloadavg()[0], 2), **fields}
        self.events.write(json.dumps(record) + "\n")
        print(f"[{record['at']}] {name} {json.dumps(fields)}", flush=True)

    # -- PKI and issuer
    def pki(self) -> None:
        w = self.work
        run(["openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "3",
             "-subj", "/CN=m6-03-soak synthetic server CA", "-addext",
             "basicConstraints=critical,CA:TRUE", "-addext", "keyUsage=critical,keyCertSign,cRLSign",
             "-keyout", w / "server-ca-key.pem", "-out", w / "server-ca.pem"])
        (w / "server-ext.cnf").write_text(
            "basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\n"
            "extendedKeyUsage=serverAuth\nsubjectAltName=IP:127.0.0.1,DNS:localhost\n"
            "subjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid,issuer\n")
        run(["openssl", "req", "-new", "-newkey", "rsa:2048", "-nodes", "-subj", "/CN=localhost",
             "-keyout", w / "server-key.pem", "-out", w / "server.csr"])
        run(["openssl", "x509", "-req", "-in", w / "server.csr", "-CA", w / "server-ca.pem",
             "-CAkey", w / "server-ca-key.pem", "-CAcreateserial", "-days", "2",
             "-extfile", w / "server-ext.cnf", "-out", w / "server-cert.pem"])
        run(["openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "3",
             "-subj", "/CN=m6-03-soak synthetic device CA",
             "-keyout", w / "device-ca-key.pem", "-out", w / "device-ca.pem"])
        run(["openssl", "genpkey", "-algorithm", "RSA", "-pkeyopt", "rsa_keygen_bits:2048",
             "-out", w / "issuer-key.pem"])
        modulus = run(["openssl", "rsa", "-in", w / "issuer-key.pem", "-noout", "-modulus"]
                      ).stdout.decode().strip().split("=", 1)[1]
        (w / "jwks.json").write_text(json.dumps({"keys": [{
            "kty": "RSA", "kid": "m6-03-soak", "alg": "RS256", "use": "sig",
            "n": b64url(bytes.fromhex(modulus)), "e": "AQAB"}]}))

    def token(self, subject: str, scope: str, min_remaining: float = 60) -> str:
        """A 300-second access token, re-signed when `min_remaining` seconds
        or fewer remain."""
        if min_remaining > 240:
            raise ValueError("a 300 s token cannot cover more than 240 s with margin")
        with self.token_lock:
            cached = self.tokens.get((subject, scope))
            if cached and cached[0] - time.time() > min_remaining:
                return cached[1]
            now = int(time.time())
            header = b64url(json.dumps({"alg": "RS256", "typ": "JWT", "kid": "m6-03-soak"}).encode())
            claims = b64url(json.dumps({"iss": ISSUER, "aud": AUDIENCE, "sub": subject,
                                        "iat": now, "exp": now + 300, "scope": scope}).encode())
            signing = f"{header}.{claims}".encode()
            sig = run(["openssl", "dgst", "-sha256", "-sign", self.work / "issuer-key.pem"],
                      stdin=signing).stdout
            value = f"{header}.{claims}.{b64url(sig)}"
            self.tokens[(subject, scope)] = (now + 300, value)
            return value

    # -- forwarder
    def start_forwarder(self) -> None:
        self.forwarder_port = free_port()
        log = (self.run_dir / "forwarder.log").open("w")
        log.write(f"nonce={self.nonce} head={head_sha()} forwarder\n")
        log.flush()
        self.forwarder = spawn(
            [sys.executable, __file__, "forwarder", "--cert", str(self.work / "server-cert.pem"),
             "--key", str(self.work / "server-key.pem"), "--port", str(self.forwarder_port),
             "--upstream", f"{self.redis[0]}:{self.redis[1]}"],
            stdout=log, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL)
        deadline = time.time() + 15
        while time.time() < deadline:
            try:
                with socket.create_connection(("127.0.0.1", self.forwarder_port), timeout=1):
                    return
            except OSError:
                time.sleep(0.1)
        raise SystemExit("forwarder did not listen")

    # -- relay
    def write_relay_config(self) -> None:
        self.consumer_port = free_port()
        self.device_port = free_port()
        self.metrics_port = free_port()
        doc = (REPO / "examples" / "m1-relay.toml").read_text()
        doc = "\n".join(line for line in doc.split("\n") if not line.startswith("boot_id ="))
        w = self.work
        for key, value in (
            ("consumer_bind", json.dumps(f"127.0.0.1:{self.consumer_port}")),
            ("device_bind", json.dumps(f"127.0.0.1:{self.device_port}")),
            ("oidc_issuer", json.dumps(ISSUER)),
            ("oidc_jwks_path", tq(w / "jwks.json")),
            ("redis_url", json.dumps(f"rediss://localhost:{self.forwarder_port}/0")),
            ("redis_namespace", json.dumps(self.namespace)),
            ("device_tls_cert_chain", tq(w / "server-cert.pem")),
            ("device_tls_private_key", tq(w / "server-key.pem")),
            ("device_tls_client_ca", tq(w / "device-ca.pem")),
            ("consumer_tls_cert_chain", tq(w / "server-cert.pem")),
            ("consumer_tls_private_key", tq(w / "server-key.pem")),
            ("deployment_incarnation", json.dumps(self.namespace)),
            ("interval_seconds", str(self.rotation[0])),
            ("handshake_timeout_seconds", str(self.rotation[1])),
            ("overlap_seconds", str(self.rotation[2])),
        ):
            doc = set_key(doc, key, value)
        top = (f"redis_tls_root_ca_path = {tq(w / 'server-ca.pem')}\n"
               f"metrics_bind = \"127.0.0.1:{self.metrics_port}\"\n{self.relay_extra}")
        doc = f"{top}{doc}\n[http_forward]\nprofiles = [\"{MCP_PROFILE}\"]\n"
        self.relay_config = w / "relay.toml"
        self.relay_config.write_text(doc)

    def relay_cmd(self, *args: str) -> str:
        completed = run([self.bins / "tunnel-relay", *args, "--config", self.relay_config])
        return completed.stdout.decode()

    def start_relay(self, wait: bool = True) -> float:
        self.relay_starts += 1
        log = (self.run_dir / f"relay-{self.relay_starts}.log").open("w")
        log.write(f"nonce={self.nonce} head={head_sha()} relay start={self.relay_starts}\n")
        log.flush()
        started = time.time()
        self.relay = spawn(
            ["nice", "-n", "10", str(self.bins / "tunnel-relay"), "serve", "--config",
             str(self.relay_config)], stdout=log, stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL, env={**os.environ, "RUST_LOG": "warn"})
        self.relay_procs.append(self.relay)
        if wait:
            deadline = time.time() + 30
            path = self.run_dir / f"relay-{self.relay_starts}.log"
            while time.time() < deadline:
                if "tunnel-relay listening" in path.read_text(errors="replace"):
                    break
                if self.relay.poll() is not None:
                    raise SystemExit(f"relay exited: {path.read_text()[-1500:]}")
                time.sleep(0.1)
            else:
                raise SystemExit("relay not listening within 30 s")
        return time.time() - started

    # -- catalog
    def provision(self) -> None:
        """First device (`a`), first user and the echo service, from the shipped records."""
        self.write_relay_config()
        records = (REPO / "examples" / "m6-catalog.toml").read_text()
        ids = {table: re.search(rf"^\[{table}\]\nid = \"([^\"]+)\"", records, re.M).group(1)
               for table in ("tenant", "user", "device", "service")}
        subject = re.search(r'^oidc_subject = "([^"]+)"', records, re.M).group(1)
        self.tenant = ids["tenant"]
        self.users["a"] = {"id": ids["user"], "subject": subject}
        device_dir = self.new_device_dir("a", ids["device"], {ids["service"]: "echo"})
        (device_dir / "catalog.toml").write_text(records)
        # A fresh CI runner's first Redis connection has failed at
        # connection_establishment (class=io) before any write; retry that
        # stage only, and record every retry.
        for attempt in range(1, 6):
            completed = run([self.bins / "tunnel-relay", "activate-first-incarnation", "--config",
                             self.relay_config], check=False)
            if completed.returncode == 0:
                break
            stderr = completed.stderr.decode(errors="replace")
            if attempt == 1:
                self.event("activate-diagnostics", **self.redis_diagnostics())
            if "stage=connection_establishment" not in stderr or attempt == 5:
                raise SystemExit(f"activate-first-incarnation failed: {stderr[-600:]}")
            self.event("activate-retry", attempt=attempt, stderr=stderr.strip()[-200:])
            time.sleep(3)
        self.relay_cmd("provision-catalog", "--records", str(device_dir / "catalog.toml"))
        self.devices["a"]["echo"] = ids["service"]
        self.event("provisioned", namespace=self.namespace, device="a")

    def new_device_dir(self, name: str, device_id: str, exports: dict[str, str]) -> Path:
        d = self.work / f"device-{name}"
        d.mkdir(exist_ok=True)
        doc = (REPO / "examples" / "m1-client.toml").read_text()
        doc = set_key(doc, "device_id", json.dumps(device_id))
        doc = set_key(doc, "relay_url",
                      json.dumps(f"wss://127.0.0.1:{self.device_port}/v1/tunnel/control"))
        for key, value in zip(("interval_seconds", "handshake_timeout_seconds", "overlap_seconds"),
                              self.rotation):
            doc = set_key(doc, key, str(value))
        # Replace the example's single export table with this device's exports.
        lines = doc.split("\n")
        start = next(i for i, line in enumerate(lines) if line.startswith("[exports."))
        end = next((i for i in range(start, len(lines)) if not lines[i].strip()), len(lines))
        tables = []
        for service, kind in exports.items():
            if kind == "echo":
                tables.append(f"[exports.\"{service}\"]\ntype = \"echo\"\n"
                              f"device_canary = \"{CANARY.decode()}\"\n")
            else:
                ws = d / "mcp-workspace"
                ws.mkdir(exist_ok=True)
                tables.append(
                    f"[exports.\"{service}\"]\ntype = \"http-forward\"\n\n"
                    f"[exports.\"{service}\".mcp]\nprofile = \"{MCP_PROFILE}\"\n\n"
                    f"[exports.\"{service}\".mcp.backend]\nkind = \"stdio\"\n"
                    f"command = {tq(self.bins / 'tunnel-mcp-fixture')}\nargs = [\"stdio\"]\n"
                    f"workspace = {tq(ws)}\n")
        doc = "\n".join(lines[:start] + ["\n".join(tables).rstrip()] + lines[end:]) + "\n"
        config = d / "client.toml"
        config.write_text(doc)
        run([self.bins / "tunnel-client", "credentials", "create", "--config", config,
             "--csr-out", "device.csr"])
        (d / "ext.cnf").write_text(
            "basicConstraints=CA:FALSE\nkeyUsage=digitalSignature\nextendedKeyUsage=clientAuth\n"
            f"subjectAltName=URI:urn:agent-tunnel:device:{device_id}\n")
        run(["openssl", "x509", "-req", "-in", d / "device.csr", "-CA", self.work / "device-ca.pem",
             "-CAkey", self.work / "device-ca-key.pem", "-CAcreateserial", "-days", "2",
             "-extfile", d / "ext.cnf", "-out", d / "device-cert.pem"])
        run([self.bins / "tunnel-client", "credentials", "import", "--config", config,
             "--certificate", "device-cert.pem", "--server-ca", self.work / "server-ca.pem"])
        self.devices[name] = {"id": device_id, "dir": d, "config": config, "proc": None,
                              "starts": 0, "exports": dict(exports)}
        return d

    def redis_diagnostics(self) -> dict:
        """Which hop refuses: the upstream Redis, or the forwarder per address family."""
        out: dict[str, str] = {}
        try:
            out["upstream_ping"] = resp(self.redis[0], self.redis[1], ["PING"]).decode(errors="replace").strip()
        except OSError as error:
            out["upstream_ping"] = f"error {type(error).__name__}: {error}"
        out["localhost_resolves"] = ",".join(sorted({a[4][0] for a in socket.getaddrinfo(
            "localhost", self.forwarder_port, type=socket.SOCK_STREAM)}))
        for host in ("127.0.0.1", "::1"):
            try:
                with socket.create_connection((host, self.forwarder_port), timeout=3):
                    out[f"forwarder_{host}"] = "connect ok"
            except OSError as error:
                out[f"forwarder_{host}"] = f"error {type(error).__name__}"
        out["forwarder_alive"] = str(self.forwarder.poll() is None)
        return out

    def add_user(self, name: str) -> None:
        user_id, subject = str(uuid.uuid4()), f"m6-03-soak-user-{name}-{self.nonce}"
        doc = self.work / f"user-{name}.toml"
        doc.write_text(f"[user]\ntenant = \"{self.tenant}\"\nid = \"{user_id}\"\n"
                       f"display_name = \"Soak user {name}\"\noidc_subject = \"{subject}\"\n")
        self.relay_cmd("add-user", "--records", str(doc))
        self.users[name] = {"id": user_id, "subject": subject}

    def add_device(self, name: str, owner: str, exports: dict[str, str]) -> None:
        """A device owned by `owner`, with services named `echo`/`mcp` in `exports`."""
        device_id = str(uuid.uuid4())
        services = {str(uuid.uuid4()): kind for kind in exports}
        d = self.new_device_dir(name, device_id, services)
        doc = d / "device.toml"
        doc.write_text(f"[device]\ntenant = \"{self.tenant}\"\nowner = \"{self.users[owner]['id']}\"\n"
                       f"id = \"{device_id}\"\ndisplay_name = \"Soak device {name}\"\n"
                       f"certificate = \"device-cert.pem\"\n")
        self.relay_cmd("add-device", "--records", str(doc))
        for service, kind in services.items():
            self.add_service(name, service, kind)
            self.grant(owner, name, kind)

    def add_service(self, device: str, service: str, kind: str) -> None:
        dev = self.devices[device]
        body = (f"[service]\ntenant = \"{self.tenant}\"\ndevice = \"{dev['id']}\"\n"
                f"id = \"{service}\"\n")
        if kind == "echo":
            body += "type = \"echo\"\ndisplay_name = \"Soak echo\"\noperations = [\"echo:invoke\"]\n"
        else:
            body += ("type = \"http-forward\"\ndisplay_name = \"Soak MCP\"\n"
                     f"operations = [\"http:invoke\"]\nhttp_forward_profile = \"{MCP_PROFILE}\"\n")
        doc = dev["dir"] / f"service-{kind}.toml"
        doc.write_text(body)
        self.relay_cmd("add-service", "--records", str(doc))
        dev[kind] = service
        dev["exports"][service] = kind

    def add_mcp_to_device(self, device: str) -> None:
        """Add an MCP service to an existing device and rewrite its profile's exports."""
        dev = self.devices[device]
        service = str(uuid.uuid4())
        self.add_service(device, service, "mcp")
        ws = dev["dir"] / "mcp-workspace"
        ws.mkdir(exist_ok=True)
        with dev["config"].open("a") as handle:
            handle.write(
                f"\n[exports.\"{service}\"]\ntype = \"http-forward\"\n\n"
                f"[exports.\"{service}\".mcp]\nprofile = \"{MCP_PROFILE}\"\n\n"
                f"[exports.\"{service}\".mcp.backend]\nkind = \"stdio\"\n"
                f"command = {tq(self.bins / 'tunnel-mcp-fixture')}\nargs = [\"stdio\"]\n"
                f"workspace = {tq(ws)}\n")

    def grant(self, user: str, device: str, kind: str) -> None:
        dev = self.devices[device]
        op = "echo:invoke" if kind == "echo" else "http:invoke"
        doc = self.work / f"grant-{user}-{device}-{kind}.toml"
        doc.write_text(f"[grant]\ntenant = \"{self.tenant}\"\nuser = \"{self.users[user]['id']}\"\n"
                       f"device = \"{dev['id']}\"\nservice = \"{dev[kind]}\"\n"
                       f"operations = [\"{op}\"]\n")
        self.relay_cmd("set-grant", "--records", str(doc))

    # -- devices
    def start_device(self, name: str) -> None:
        dev = self.devices[name]
        previous = dev.get("proc")
        if previous is not None and previous.poll() is None:
            # Never orphan a live device by overwriting its handle.
            self.event("device-still-running", device=name, pid=previous.pid)
            stop_group(previous, timeout=10)
        dev["starts"] += 1
        out = (self.run_dir / f"device-{name}-{dev['starts']}.jsonl").open("w")
        err = (self.run_dir / f"device-{name}-{dev['starts']}.stderr.log").open("w")
        err.write(f"nonce={self.nonce} head={head_sha()} device={name} start={dev['starts']}\n")
        err.flush()
        dev["proc"] = spawn(
            ["nice", "-n", "10", str(self.bins / "tunnel-client"), "connect", "--config",
             str(dev["config"]), "--json"], stdout=out, stderr=err, stdin=subprocess.DEVNULL,
            env={**os.environ, "RUST_LOG": "warn"})
        dev.setdefault("all_procs", []).append(dev["proc"])
        self.event("device-start", device=name, start=dev["starts"], pid=dev["proc"].pid)

    def device_sessions(self, name: str) -> tuple[list[str], int, list[dict]]:
        """(distinct session ids, max rotations_completed, raw events) over all starts."""
        sessions, rotations, events = [], 0, []
        for path in sorted(self.run_dir.glob(f"device-{name}-*.jsonl")):
            for line in path.read_text(errors="replace").splitlines():
                try:
                    value = json.loads(line)
                except ValueError:
                    continue
                events.append(value)
                result = value.get("result") if isinstance(value, dict) else None
                if isinstance(result, dict):
                    session = result.get("session_id")
                    if session and session not in sessions:
                        sessions.append(session)
                    rotations = max(rotations, int(result.get("rotations_completed") or 0))
        return sessions, rotations, events

    # -- teardown
    def close(self) -> None:
        # Whole process groups, so a device's MCP children and anything a
        # killed relay left behind go too; each group is signalled even when
        # its leader already exited.
        for dev in self.devices.values():
            for proc in dev.get("all_procs", []):
                stop_group(proc)
        for proc in self.relay_procs + [self.forwarder]:
            stop_group(proc)
        try:
            removed = delete_namespace(self.redis[0], self.redis[1], self.namespace)
            self.event("namespace-deleted", namespace=self.namespace, keys=removed)
        except OSError as error:
            self.event("namespace-delete-failed", error=str(error))
        self.events.close()


# ------------------------------------------------------------- the sampler

def rss_kib(pid: int) -> int | None:
    out = subprocess.run(["ps", "-o", "rss=", "-p", str(pid)], capture_output=True, text=True)
    text = out.stdout.strip()
    return int(text) if text.isdigit() else None


def fd_count(pid: int) -> int | None:
    proc = Path(f"/proc/{pid}/fd")
    if proc.is_dir():  # Linux: exact descriptor count, no lsof needed
        try:
            return len(os.listdir(proc))
        except OSError:
            return None
    out = subprocess.run(["lsof", "-n", "-P", "-p", str(pid)], capture_output=True, text=True)
    lines = out.stdout.strip().splitlines()
    return max(0, len(lines) - 1) if lines else None


METRIC_SERIES = ("tunnel_relay_device_sessions", "tunnel_relay_device_sockets",
                 "tunnel_relay_streams", "tunnel_relay_sessions_rotating",
                 "tunnel_relay_queue_bytes", "tunnel_relay_replay_bytes",
                 "tunnel_relay_consumer_refusals_total", "tunnel_relay_consumer_write_timeouts_total",
                 "tunnel_relay_ready", "tunnel_relay_actor_commands_total",
                 "tunnel_relay_actor_busy_microseconds_total", "tunnel_relay_actor_queue_depth")


def scrape_metrics(port: int) -> dict[str, float]:
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=3) as sock:
            sock.sendall(b"GET /metrics HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n")
            data = b""
            while True:
                chunk = sock.recv(65536)
                if not chunk:
                    break
                data += chunk
    except OSError:
        return {}
    values: dict[str, float] = {}
    for line in data.decode(errors="replace").splitlines():
        if line.startswith("#"):
            continue
        parts = line.rsplit(" ", 1)
        if len(parts) != 2:
            continue
        name = parts[0].split("{", 1)[0]
        if name in METRIC_SERIES:
            try:
                values[name] = values.get(name, 0.0) + float(parts[1])
            except ValueError:
                pass
    return values


class Sampler(threading.Thread):
    def __init__(self, stack: Stack, interval: float = 15.0, fd_every: int = 4):
        super().__init__(daemon=True)
        self.stack = stack
        self.interval = interval
        self.fd_every = fd_every
        self.stop_flag = threading.Event()
        self.path = stack.run_dir / "samples.csv"
        self.handle = self.path.open("w", newline="")
        self.handle.write(f"# nonce={stack.nonce} head={head_sha()} samples\n")
        self.writer = csv.writer(self.handle)
        self.writer.writerow(["t", "load1", "process", "pid", "rss_kib", "fds", *METRIC_SERIES])

    def run(self) -> None:
        tick = 0
        while not self.stop_flag.is_set():
            procs = [("relay", self.stack.relay), ("forwarder", self.stack.forwarder)]
            procs += [(f"device-{n}", d.get("proc")) for n, d in self.stack.devices.items()]
            metrics = scrape_metrics(self.stack.metrics_port) if hasattr(self.stack, "metrics_port") else {}
            now = round(time.time(), 1)
            for name, proc in procs:
                if not proc or proc.poll() is not None:
                    continue
                fds = fd_count(proc.pid) if tick % self.fd_every == 0 else ""
                row = [now, round(os.getloadavg()[0], 2), name, proc.pid, rss_kib(proc.pid), fds]
                row += [metrics.get(s, "") if name == "relay" else "" for s in METRIC_SERIES]
                self.writer.writerow(row)
            self.handle.flush()
            tick += 1
            self.stop_flag.wait(self.interval)

    def stop(self) -> None:
        self.stop_flag.set()
        self.join(timeout=30)
        self.handle.close()


# ------------------------------------------------------------ the load gen

class Recorder:
    FIELDS = ["t", "kind", "worker", "phase", "latency_ms", "status", "code", "execution", "ok",
              "detail"]

    def __init__(self, path: Path, nonce: str):
        self.handle = path.open("w", newline="")
        self.handle.write(f"# nonce={nonce} head={head_sha()} requests\n")
        self.writer = csv.writer(self.handle)
        self.writer.writerow(self.FIELDS)
        self.rows: list[tuple] = []
        self.phase = "run"
        self.count = 0

    def add(self, t, kind, worker, latency_ms, status, code, execution, ok, detail=""):
        row = (round(t, 3), kind, worker, self.phase, round(latency_ms, 2), status, code,
               execution, int(ok), detail)
        self.writer.writerow(row)
        self.rows.append(row)
        self.count += 1
        if self.count % 200 == 0:
            self.handle.flush()

    def close(self) -> None:
        self.handle.flush()
        self.handle.close()


class HttpConn:
    """A minimal keep-alive HTTP/1.1 client over TLS (stdlib only)."""

    def __init__(self, port: int, ctx: ssl.SSLContext):
        self.port, self.ctx = port, ctx
        self.reader = self.writer = None

    async def ensure(self) -> None:
        if self.writer is None:
            self.reader, self.writer = await asyncio.open_connection(
                "127.0.0.1", self.port, ssl=self.ctx, server_hostname="localhost")

    async def close(self) -> None:
        if self.writer is not None:
            try:
                self.writer.close()
            except Exception:  # noqa: BLE001
                pass
        self.reader = self.writer = None

    async def request(self, method: str, path: str, headers: dict[str, str],
                      body: bytes) -> tuple[int, dict[str, str], bytes]:
        await self.ensure()
        head = f"{method} {path} HTTP/1.1\r\nHost: localhost\r\nContent-Length: {len(body)}\r\n"
        head += "".join(f"{k}: {v}\r\n" for k, v in headers.items()) + "\r\n"
        self.writer.write(head.encode() + body)
        await self.writer.drain()
        status_line = await self.reader.readline()
        if not status_line:
            raise ConnectionError("closed before status")
        status = int(status_line.split()[1])
        response_headers: dict[str, str] = {}
        while True:
            line = await self.reader.readline()
            if line in (b"\r\n", b"\n", b""):
                break
            name, _, value = line.decode("latin-1").partition(":")
            response_headers[name.strip().lower()] = value.strip()
        data = b""
        if status in (204, 304) or 100 <= status < 200:
            pass  # no body by definition (a DELETE answers 204 without Content-Length)
        elif response_headers.get("transfer-encoding", "").lower() == "chunked":
            while True:
                size = int((await self.reader.readline()).split(b";")[0].strip(), 16)
                if size == 0:
                    await self.reader.readline()
                    break
                data += await self.reader.readexactly(size)
                await self.reader.readexactly(2)
        elif "content-length" in response_headers:
            data = await self.reader.readexactly(int(response_headers["content-length"]))
        else:
            data = await self.reader.read()
            await self.close()
        if response_headers.get("connection", "").lower() == "close":
            await self.close()
        return status, response_headers, data


def classify(status: int, body: bytes) -> tuple[str, str]:
    if status == 200:
        return "", ""
    # The relay's flat-body routes answer {"code","execution",...}; the
    # http-forward gateway nests the same pair under "error".
    try:
        value = json.loads(body)
    except ValueError:
        value = None
    if isinstance(value, dict):
        error = value.get("error") if isinstance(value.get("error"), dict) else value
        if "code" in error:
            return str(error["code"]), str(error.get("execution", ""))
    return f"HTTP_{status}", ""


def client_ctx(stack: Stack) -> ssl.SSLContext:
    ctx = ssl.create_default_context(cafile=str(stack.work / "server-ca.pem"))
    ctx.verify_flags &= ~getattr(ssl, "VERIFY_X509_STRICT", 0)
    return ctx


class McpSessionPool:
    """2025-11-25 MCP sessions shared by one or more workers (M6-C146).

    A stdio export holds one child, and one of its `max_children` slots
    (default 8), per session until `DELETE`, a child crash or the 600 s
    `session_idle_seconds`.  Workers therefore share a bounded number of
    sessions (concurrent POSTs on one session are routed by JSON-RPC ID) and
    whoever owns the pool DELETEs every session it opened when it is done, so
    a load step measures concurrent MCP calls instead of the leaked-session
    bound.  A session is dropped from the pool only on 404 (the export no
    longer knows it); a timeout or connection error resets the worker's
    connection, never the session, so it is not orphaned.  A session whose
    `notifications/initialized` failed is not usable: it is DELETEd at once or,
    if that fails, kept in `orphans` so `close` DELETEs it.  `stats` accounts
    for every opened session: deleted, a recorded DELETE failure, or forgotten
    on 404; anything else is `unaccounted`.
    """

    def __init__(self, size: int):
        self.sessions: list[str | None] = [None] * max(1, size)
        self.locks = [asyncio.Lock() for _ in self.sessions]
        self.opened = 0
        self.deleted = 0
        self.delete_failures: dict[str, int] = {}
        self.orphans: list[str] = []
        self.forgotten_on_404 = 0
        self.init_timeouts = 0

    def forget(self, slot: int, session: str) -> None:
        if self.sessions[slot] == session:
            self.sessions[slot] = None
            self.forgotten_on_404 += 1

    async def close(self, worker: "Worker", attempts: int = 3) -> None:
        """DELETE every open session through `worker`'s connection.

        A reset keep-alive connection or a retryable `503` (for example
        `CONNECTION_LIMIT`) is retried on a fresh connection, so a session is
        left to the export's idle expiry only after `attempts` failures.
        """
        pending = [x for x in self.sessions if x is not None] + self.orphans
        self.sessions = [None] * len(self.sessions)
        self.orphans = []
        for session in pending:
            key = ""
            for attempt in range(attempts):
                if attempt:
                    await asyncio.sleep(1.0)
                try:
                    status = await worker.delete_mcp_session(session)
                except (asyncio.TimeoutError, TimeoutError, OSError, ConnectionError,
                        asyncio.IncompleteReadError, ssl.SSLError, ValueError,
                        IndexError) as error:
                    await worker.conn.close()
                    key = f"CONN_{type(error).__name__}"
                    continue
                if status in (200, 202, 204):
                    self.deleted += 1
                    key = ""
                    break
                if status == 404:
                    key = "HTTP_404"  # already gone (crash or idle expiry)
                    break
                key = f"HTTP_{status}"
                if status != 503:
                    break
            if key:
                self.delete_failures[key] = self.delete_failures.get(key, 0) + 1

    def stats(self) -> dict:
        failures = sum(self.delete_failures.values())
        return {"size": len(self.sessions), "opened": self.opened, "deleted": self.deleted,
                "delete_failures": dict(self.delete_failures),
                "forgotten_on_404": self.forgotten_on_404,
                "init_timeouts": self.init_timeouts,
                "unaccounted": self.opened - self.deleted - failures - self.forgotten_on_404}

    def leaked(self) -> bool:
        """True if a session may still hold an export slot after `close`."""
        # Only a 404 proves the session is gone; any other DELETE failure, and
        # an initialize whose session ID never arrived, may hold a slot.
        stats = self.stats()
        return (stats["unaccounted"] != 0 or self.init_timeouts > 0
                or any(key != "HTTP_404" for key in self.delete_failures))


def report_mcp_pool(stack: "Stack", pool: McpSessionPool, where: str) -> None:
    """Make a possibly leaked session visible in the driver log (M6-C146)."""
    if pool.leaked():
        stack.event("mcp-session-leak", where=where, mcp_sessions=pool.stats())


class Worker:
    """One consumer: one keep-alive connection, echo or MCP tools/call."""

    def __init__(self, stack: Stack, rec: Recorder, kind: str, user: str, device: str,
                 worker_id: str, payload_size: int = 1024,
                 mcp_pool: McpSessionPool | None = None, mcp_slot: int = 0):
        self.stack, self.rec, self.kind, self.user, self.device = stack, rec, kind, user, device
        self.worker_id = worker_id
        self.payload_size = payload_size
        self.conn = HttpConn(stack.consumer_port, client_ctx(stack))
        self.seq = 0
        # A worker without a shared pool owns a private one-session pool and
        # DELETEs that session at shutdown.
        self.owns_pool = mcp_pool is None
        self.mcp_pool = mcp_pool if mcp_pool is not None else McpSessionPool(1)
        self.mcp_slot = mcp_slot % len(self.mcp_pool.sessions)
        self.mcp_calls_ok = 0
        # M6-C182: with `honor_retry_after`, a closed-loop worker refused
        # `CONNECTION_LIMIT` waits the refusal's `retry_after_ms` before its
        # next request instead of reconnecting at once.
        self.honor_retry_after = False
        self.retry_after_s = 0.0

    def path(self) -> str:
        dev = self.stack.devices[self.device]
        if self.kind == "echo":
            return f"/v1/devices/{dev['id']}/services/{dev['echo']}/echo"
        return f"/v1/devices/{dev['id']}/services/{dev['mcp']}/http/mcp"

    async def call(self, method: str, headers: dict, body: bytes, timeout: float = 40.0):
        return await asyncio.wait_for(self.conn.request(method, self.path(), headers, body), timeout)

    async def once(self) -> None:
        self.seq += 1
        t0 = time.time()
        body = b""
        start = time.perf_counter()
        user = self.stack.users[self.user]["subject"]
        try:
            if self.kind == "echo":
                token = await asyncio.to_thread(self.stack.token, user, "echo:invoke")
                payload = (f"{self.worker_id}:{self.seq}:".encode() * (self.payload_size // 8 + 1)
                           )[: self.payload_size]
                status, _, body = await self.call("POST", {
                    "Authorization": f"Bearer {token}",
                    "Content-Type": "application/octet-stream"}, payload)
                code, execution = classify(status, body)
                ok = status == 200 and body == CANARY + payload
                if status == 200 and not ok:
                    code = "INTEGRITY_MISMATCH"
            else:
                token = await asyncio.to_thread(self.stack.token, user, "http:invoke")
                status, body, code, execution, ok = await self.mcp_call(token)
        except (asyncio.TimeoutError, TimeoutError):
            await self.conn.close()
            status, code, execution, ok = 0, "CLIENT_TIMEOUT", "unknown", False
        except (OSError, ConnectionError, asyncio.IncompleteReadError, ssl.SSLError, ValueError,
                IndexError) as error:
            await self.conn.close()
            status, code, execution, ok = 0, f"CONN_{type(error).__name__}", "", False
        latency = (time.perf_counter() - start) * 1000
        if code == "CONNECTION_LIMIT":
            try:
                self.retry_after_s = float(json.loads(body).get("retry_after_ms", 1000)) / 1000
            except (ValueError, AttributeError):
                self.retry_after_s = 1.0
        # An unclassified refusal keeps a short printable prefix of its body
        # (a relay or fixture error text, never a request payload).
        detail = ""
        if code.startswith("HTTP_") and status and status != 200:
            detail = re.sub(r"[^ -~]", "?", body[:80].decode("latin-1"))
        self.rec.add(t0, self.kind, self.worker_id, latency, status, code, execution, ok, detail)

    def mcp_headers(self, token: str) -> dict:
        return {"Authorization": f"Bearer {token}", "Content-Type": "application/json",
                "Accept": "application/json, text/event-stream"}

    async def mcp_initialize(self, base: dict):
        """Open one session; returns (session, None) or (None, failure tuple)."""
        init = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {
            "protocolVersion": "2025-11-25", "capabilities": {},
            "clientInfo": {"name": "m6-03-soak", "version": "1"}}}).encode()
        try:
            status, headers, body = await self.call("POST", base, init)
        except (asyncio.TimeoutError, TimeoutError):
            # The export may have opened a session whose ID never arrived; only
            # its idle expiry can end it.  Counted so the step shows it.
            self.mcp_pool.init_timeouts += 1
            raise
        if status != 200 or "mcp-session-id" not in headers:
            code, execution = classify(status, body)
            return None, (status, body, code or "MCP_INIT_NO_SESSION", execution, False)
        session = headers["mcp-session-id"]
        self.mcp_pool.opened += 1
        hdrs = {**base, "mcp-protocol-version": "2025-11-25", "mcp-session-id": session}
        try:
            status, _, body = await self.call(
                "POST", hdrs, b'{"jsonrpc":"2.0","method":"notifications/initialized"}')
        except BaseException:
            # A timeout or connection error here must not orphan the session:
            # the pool's close DELETEs it.  The caller records the error.
            self.mcp_pool.orphans.append(session)
            raise
        if status != 202:
            # Not usable: DELETE it rather than leave it holding a child slot;
            # if that fails, the pool's close tries again.
            deleted = False
            try:
                deleted = await self.delete_mcp_session(session) in (200, 202, 204)
            except (asyncio.TimeoutError, TimeoutError, OSError, ConnectionError,
                    asyncio.IncompleteReadError, ssl.SSLError, ValueError, IndexError):
                await self.conn.close()
            if deleted:
                self.mcp_pool.deleted += 1
            else:
                self.mcp_pool.orphans.append(session)
            code, execution = classify(status, body)
            return None, (status, body, code, execution, False)
        return session, None

    async def delete_mcp_session(self, session: str) -> int:
        token = await asyncio.to_thread(self.stack.token, self.stack.users[self.user]["subject"],
                                        "http:invoke")
        hdrs = {"Authorization": f"Bearer {token}", "mcp-protocol-version": "2025-11-25",
                "mcp-session-id": session}
        status, _, _ = await self.call("DELETE", hdrs, b"", timeout=15.0)
        return status

    async def mcp_call(self, token: str):
        base = self.mcp_headers(token)
        pool, slot = self.mcp_pool, self.mcp_slot
        session = pool.sessions[slot]
        if session is None:
            async with pool.locks[slot]:
                session = pool.sessions[slot]
                if session is None:
                    session, failure = await self.mcp_initialize(base)
                    if failure is not None:
                        return failure
                    pool.sessions[slot] = session
        hdrs = {**base, "mcp-protocol-version": "2025-11-25", "mcp-session-id": session}
        marker = f"{self.worker_id}-{self.seq}"
        call = json.dumps({"jsonrpc": "2.0", "id": marker, "method": "tools/call",
                           "params": {"name": "echo", "arguments": {"marker": marker}}}).encode()
        status, _, body = await self.call("POST", hdrs, call)
        code, execution = classify(status, body)
        ok = False
        if status == 200:
            text = body.decode(errors="replace")
            if "data:" in text and "{" in text:
                text = text[text.index("{"):]
            ok = marker in text
            if not ok:
                code = "INTEGRITY_MISMATCH"
            else:
                self.mcp_calls_ok += 1
        elif status == 404:
            pool.forget(slot, session)
        return status, body, code, execution, ok

    async def loop_rate(self, rate: float, until: float) -> None:
        interval = 1.0 / rate
        next_at = time.time()
        while time.time() < until:
            await self.once()
            next_at += interval
            delay = next_at - time.time()
            if delay > 0:
                await asyncio.sleep(delay)
            else:
                next_at = time.time()

    async def loop_closed(self, until: float) -> None:
        while time.time() < until:
            await self.once()
            if self.honor_retry_after and self.retry_after_s:
                await asyncio.sleep(min(self.retry_after_s, max(0.0, until - time.time())))
            self.retry_after_s = 0.0

    async def shutdown(self) -> None:
        if self.owns_pool:
            await self.mcp_pool.close(self)
            if self.kind == "mcp":
                report_mcp_pool(self.stack, self.mcp_pool, self.worker_id)
        await self.conn.close()


# ------------------------------------ generator attribution (M6-C182, M6-C183)
#
# Every in-process worker shares this driver's single asyncio event loop (and
# its one Python thread).  A request's latency is measured on that loop, so it
# includes the time the loop spends running every other worker's callbacks.
# The helpers below separate the generator from the relay: `LoopLag` measures
# the driver loop's own scheduling delay, `cpu_seconds` accounts each process's
# CPU, and `start_clients` runs workers in separate `client` subprocesses, each
# with its own loop, so the same request code is timed off the flooding loop.

def cpu_seconds(pid: int) -> float | None:
    """Cumulative user + system CPU seconds of one process (no payload)."""
    stat = Path(f"/proc/{pid}/stat")
    if stat.exists():  # Linux: tick resolution
        try:
            fields = stat.read_text().rsplit(")", 1)[1].split()
            return (int(fields[11]) + int(fields[12])) / os.sysconf("SC_CLK_TCK")
        except (OSError, IndexError, ValueError):
            return None
    out = subprocess.run(["ps", "-o", "time=", "-p", str(pid)], capture_output=True, text=True)
    text = out.stdout.strip()
    if not text:
        return None
    days, _, clock = text.rpartition("-")
    total = 0.0
    for part in clock.split(":"):
        total = total * 60 + float(part)
    return total + (int(days) * 86400 if days else 0)


def cpu_snapshot(stack: Stack) -> tuple[float, dict[str, float]]:
    procs = [("relay", stack.relay), ("forwarder", stack.forwarder)]
    procs += [(f"device-{n}", d.get("proc")) for n, d in stack.devices.items()]
    out: dict[str, float] = {}
    for name, proc in procs:
        if proc is not None and proc.poll() is None:
            value = cpu_seconds(proc.pid)
            if value is not None:
                out[name] = value
    own = os.times()
    out["driver"] = own.user + own.system
    out.update(redis_counters(stack.redis))
    metrics = scrape_metrics(stack.metrics_port) if hasattr(stack, "metrics_port") else {}
    if "tunnel_relay_actor_busy_microseconds_total" in metrics:
        out["relay_actor"] = metrics["tunnel_relay_actor_busy_microseconds_total"] / 1e6
        out["relay_actor_commands"] = metrics.get("tunnel_relay_actor_commands_total", 0.0)
    return time.perf_counter(), out


def redis_counters(redis: tuple[str, int]) -> dict[str, float]:
    """The Redis server's CPU seconds and script/command totals (INFO; no
    keys or values).  On a shared Redis these include other clients' work."""
    try:
        text = resp(redis[0], redis[1], ["INFO", "all"]).decode(errors="replace")
    except OSError:
        return {}
    out: dict[str, float] = {}
    for line in text.splitlines():
        name, _, value = line.partition(":")
        if name in ("used_cpu_sys", "used_cpu_user"):
            out["redis"] = out.get("redis", 0.0) + float(value)
        elif name == "total_commands_processed":
            out["redis_commands"] = float(value)
        elif name.startswith("cmdstat_eval"):
            fields = dict(item.split("=", 1) for item in value.split(",") if "=" in item)
            out["redis_script_calls"] = out.get("redis_script_calls", 0.0) + float(fields.get("calls", 0))
            out["redis_script_usec"] = out.get("redis_script_usec", 0.0) + float(fields.get("usec", 0))
    return out


def cpu_percent(before: tuple[float, dict[str, float]],
                after: tuple[float, dict[str, float]]) -> dict[str, float]:
    """CPU use per process over an interval, in percent of one CPU (for
    `relay_actor`, the single relay actor's busy wall time in percent); Redis
    and relay actor command counts as rates per second, and script time per
    call."""
    span = after[0] - before[0]
    if span <= 0:
        return {}
    delta = {name: after[1][name] - before[1][name] for name in after[1] if name in before[1]}
    out = {}
    for name, value in delta.items():
        if name in ("redis_commands", "redis_script_calls", "relay_actor_commands"):
            out[f"{name}_per_s"] = round(value / span, 1)
        elif name != "redis_script_usec":
            out[name] = round(value / span * 100, 1)
    if delta.get("redis_script_calls"):
        out["redis_script_usec_per_call"] = round(delta.get("redis_script_usec", 0.0)
                                                  / delta["redis_script_calls"], 1)
    return out


class LoopLag:
    """How late a 10 ms sleep wakes on this process's event loop.  With a
    saturated loop, every request timed on it is delayed by about this much."""

    def __init__(self, interval: float = 0.01):
        self.interval = interval
        self.samples: list[float] = []

    async def run(self, until: float) -> None:
        while time.time() < until:
            start = time.perf_counter()
            await asyncio.sleep(self.interval)
            self.samples.append((time.perf_counter() - start - self.interval) * 1000)

    def summary(self) -> dict:
        def pct(value: float) -> float | None:
            found = percentile(self.samples, value)
            return None if found is None else round(found, 2)
        return {"samples": len(self.samples), "p50": pct(50), "p99": pct(99),
                "max": round(max(self.samples), 2) if self.samples else None}


class _ClientStack:
    """The subset of `Stack` a `Worker` uses, for a `client` subprocess."""

    def __init__(self, cfg: dict):
        self.consumer_port = cfg["port"]
        self.work = Path(cfg["work"])
        self.users = {"u": {"subject": cfg["subject"]}}
        self.devices = {"d": {"id": cfg["device_id"], "echo": cfg["echo"]}}
        self._token = cfg["token"]

    def token(self, subject: str, scope: str) -> str:
        return self._token


async def client_main_async(cfg: dict) -> dict:
    stack = _ClientStack(cfg)
    rec = Recorder(Path(cfg["csv"]), cfg["nonce"])
    rec.phase = cfg["phase"]
    workers = [Worker(stack, rec, "echo", "u", "d", f"{cfg['prefix']}-{i}",
                      payload_size=cfg["payload"]) for i in range(cfg["workers"])]
    for w in workers:
        w.honor_retry_after = bool(cfg.get("honor_retry_after"))
    if cfg.get("preconnect"):
        # Open (and hold) each keep-alive connection before the caller starts
        # anything else, so this client is measured as an already-connected
        # consumer rather than one competing for a listener permit.
        for w in workers:
            await asyncio.wait_for(w.conn.ensure(), 30)
    print(json.dumps({"ready": True}), flush=True)
    lag = LoopLag()
    until = cfg["until"]
    loops = [w.loop_rate(cfg["rate"], until) if cfg["rate"] else w.loop_closed(until)
             for w in workers]
    await asyncio.gather(lag.run(until), *loops)
    for w in workers:
        await w.shutdown()
    rec.close()
    own = os.times()
    return {"rows": rec.count, "loop_lag_ms": lag.summary(),
            "cpu_s": round(own.user + own.system, 3)}


def client_main() -> None:
    """`client`: echo workers on this process's own event loop.  The
    configuration, including the token, arrives on stdin, never in argv; one
    JSON summary line is printed on stdout."""
    cfg = json.loads(sys.stdin.read())
    print(json.dumps(asyncio.run(client_main_async(cfg))), flush=True)


async def start_clients(stack: Stack, rec: Recorder, user: str, device: str, prefix: str,
                        workers: int, processes: int, until: float, rate: float = 0.0,
                        payload: int = 1024, preconnect: bool = False,
                        honor_retry_after: bool = False):
    """Start `workers` echo workers split across `processes` `client`
    subprocesses, running until `until`, and return once every process is
    ready (with `preconnect`, once its connections are open).  Await the
    returned coroutine to merge their rows into `rec` under the current
    phase; it returns each process's loop lag and CPU seconds."""
    dev = stack.devices[device]
    # A client process holds one token for its whole run (it cannot re-sign),
    # so it must outlive `until` with the usual 60 s margin.
    token = await asyncio.to_thread(stack.token, stack.users[user]["subject"], "echo:invoke",
                                    max(0.0, until - time.time()) + 60)
    shares = [workers // processes + (1 if i < workers % processes else 0)
              for i in range(processes)]
    procs = []
    for index, share in enumerate(s for s in shares if s):
        csv_path = stack.run_dir / f"client-{prefix}-{index}.csv"
        cfg = {"port": stack.consumer_port, "work": str(stack.work),
               "subject": stack.users[user]["subject"], "device_id": dev["id"],
               "echo": dev["echo"], "token": token, "csv": str(csv_path), "nonce": stack.nonce,
               "phase": rec.phase, "prefix": f"{prefix}-p{index}", "workers": share,
               "rate": rate, "payload": payload, "until": until, "preconnect": preconnect,
               "honor_retry_after": honor_retry_after}
        proc = await asyncio.create_subprocess_exec(
            sys.executable, str(Path(__file__).resolve()), "client",
            stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE,
            start_new_session=True)
        proc.stdin.write(json.dumps(cfg).encode())
        await proc.stdin.drain()
        proc.stdin.close()
        procs.append((proc, csv_path))
    for proc, _ in procs:
        await asyncio.wait_for(proc.stdout.readline(), 60)  # {"ready": true}
    return _finish_clients(rec, procs)


async def _finish_clients(rec: Recorder, procs: list) -> dict:
    results = await asyncio.gather(*(p.communicate() for p, _ in procs))
    report = []
    for (proc, csv_path), (stdout, _) in zip(procs, results):
        lines = [line for line in csv_path.read_text().splitlines() if not line.startswith("#")]
        for row in list(csv.DictReader(lines)):
            rec.add(float(row["t"]), row["kind"], row["worker"], float(row["latency_ms"]),
                    int(row["status"]), row["code"], row["execution"], row["ok"] == "1",
                    row["detail"])
        try:
            summary = json.loads(stdout.decode().strip().splitlines()[-1])
        except (ValueError, IndexError):
            summary = {"error": f"client exited {proc.returncode} without a summary"}
        summary["exit"] = proc.returncode
        report.append(summary)
    return {"processes": report}


async def wait_serving(stack: Stack, rec: Recorder, device: str = "a", user: str = "a",
                       kind: str = "echo", timeout: float = 60) -> float:
    """Seconds until the first 200 through the relay; warm-up rows are phase=warmup."""
    phase, rec.phase = rec.phase, "warmup"
    worker = Worker(stack, rec, kind, user, device, f"warm-{device}-{kind}")
    start = time.time()
    try:
        while time.time() - start < timeout:
            before = len(rec.rows)
            await worker.once()
            if rec.rows[before][5] == 200:
                return time.time() - start
            await asyncio.sleep(0.2)
        raise SystemExit(f"device {device} not serving {kind} within {timeout} s")
    finally:
        await worker.shutdown()
        rec.phase = phase


# -------------------------------------------------------------- summaries

def summarize_rows(rows: list[tuple], kind: str | None = None, phase: str | None = None) -> dict:
    sel = [r for r in rows if (kind is None or r[1] == kind) and (phase is None or r[3] == phase)]
    ok_lat = [r[4] for r in sel if r[8] == 1]
    codes: dict[str, int] = {}
    for r in sel:
        if r[8] != 1:
            key = r[6] or f"HTTP_{r[5]}"
            if r[7]:
                key += f"/{r[7]}"
            if key.startswith("HTTP_") and len(r) > 9 and r[9]:
                key += f" [{r[9][:48]}]"
            codes[key] = codes.get(key, 0) + 1
    span = (max(r[0] for r in sel) - min(r[0] for r in sel)) if len(sel) > 1 else 0
    return {
        "requests": len(sel), "ok": len(ok_lat), "errors": len(sel) - len(ok_lat),
        "errors_by_code": dict(sorted(codes.items(), key=lambda kv: -kv[1])),
        "latency_ms_ok": {"p50": percentile(ok_lat, 50), "p95": percentile(ok_lat, 95),
                          "p99": percentile(ok_lat, 99), "max": max(ok_lat) if ok_lat else None,
                          "mean": round(statistics.fmean(ok_lat), 2) if ok_lat else None},
        "throughput_ok_per_s": round(len(ok_lat) / span, 2) if span else None,
    }


def summarize_samples(path: Path) -> dict:
    out: dict[str, dict] = {}
    if not path.exists():
        return out
    rows = [line for line in path.read_text().splitlines() if not line.startswith("#")]
    reader = csv.DictReader(rows)
    series: dict[str, list[dict]] = {}
    for row in reader:
        series.setdefault(row["process"], []).append(row)
    loads = [float(r["load1"]) for items in series.values() for r in items if r.get("load1")]
    if loads:
        out["host_load1"] = {"min": min(loads), "mean": round(statistics.fmean(loads), 2),
                             "max": max(loads),
                             "samples_above_20": sum(1 for x in loads if x > 20),
                             "samples": len(loads)}
    for name, items in series.items():
        rss = [int(r["rss_kib"]) for r in items if r["rss_kib"].isdigit()]
        fds = [int(r["fds"]) for r in items if r["fds"].isdigit()]
        entry = {"samples": len(items)}
        if rss:
            n = len(rss)
            q = max(1, n // 4)
            entry.update({"rss_kib_first": rss[0], "rss_kib_last": rss[-1], "rss_kib_min": min(rss),
                          "rss_kib_max": max(rss),
                          "rss_kib_mean_second_quarter": round(statistics.fmean(rss[q:2 * q]) if n >= 4 else rss[0]),
                          "rss_kib_mean_last_quarter": round(statistics.fmean(rss[-q:]))})
        if fds:
            entry.update({"fds_first": fds[0], "fds_last": fds[-1], "fds_min": min(fds),
                          "fds_max": max(fds)})
        if name == "relay":
            for series_name in ("tunnel_relay_device_sockets", "tunnel_relay_streams",
                                "tunnel_relay_queue_bytes", "tunnel_relay_replay_bytes",
                                "tunnel_relay_sessions_rotating"):
                vals = [float(r[series_name]) for r in items if r.get(series_name)]
                if vals:
                    entry[f"{series_name}_max"] = max(vals)
                    entry[f"{series_name}_last"] = vals[-1]
            for counter in ("tunnel_relay_consumer_refusals_total",
                            "tunnel_relay_consumer_write_timeouts_total"):
                vals = [float(r[counter]) for r in items if r.get(counter)]
                if vals:
                    entry[f"{counter}_last"] = vals[-1]
        out[name] = entry
    return out


def write_summary(run_dir: Path, summary: dict) -> None:
    (run_dir / "summary.json").write_text(json.dumps(summary, indent=2, default=str) + "\n")
    print(json.dumps(summary, indent=2, default=str))


# ------------------------------------------------------------ experiments

def wait_for_quiet(max_load: float) -> None:
    """Refuse to measure on a starved host: wait until the 1-minute load is below max_load."""
    while os.getloadavg()[0] >= max_load:
        print(f"[{now_iso()}] waiting: load1={os.getloadavg()[0]:.1f} >= {max_load}", flush=True)
        time.sleep(30)


def make_run(args: argparse.Namespace, name: str) -> tuple[Path, str]:
    wait_for_quiet(args.max_load)
    nonce = uuid.uuid4().hex[:12]
    run_dir = Path(args.logs) / f"{name}-{time.strftime('%Y%m%dT%H%M%S')}-{nonce}"
    run_dir.mkdir(parents=True)
    (run_dir / "run.txt").write_text(
        f"nonce={nonce} head={head_sha()} experiment={name} started={now_iso()} "
        f"bins={args.bin_dir} bins_source_head={args.bin_head} host={os.uname().nodename} cpus={os.cpu_count()} "
        f"loadavg={os.getloadavg()} argv={sys.argv[1:]}\n")
    return run_dir, nonce


def base_stack(args, run_dir, nonce, tag, redis=None, mcp=True, **kw) -> Stack:
    stack = Stack(Path(args.bin_dir), run_dir, redis or parse_redis(args.redis), tag, nonce, **kw)
    stack.pki()
    stack.start_forwarder()
    stack.provision()
    if mcp:
        stack.add_mcp_to_device("a")
        stack.grant("a", "a", "mcp")
    return stack


def parse_redis(text: str) -> tuple[str, int]:
    host, port = text.rsplit(":", 1)
    return host, int(port)


async def soak(args: argparse.Namespace) -> None:
    run_dir, nonce = make_run(args, "soak")
    stack = base_stack(args, run_dir, nonce, "m6-03-soak")
    rec = Recorder(run_dir / "requests.csv", nonce)
    sampler = None
    try:
        stack.start_relay()
        stack.start_device("a")
        sampler = Sampler(stack, interval=args.sample_interval)
        sampler.start()
        stack.event("warmup", seconds=await wait_serving(stack, rec))
        await wait_serving(stack, rec, kind="mcp")
        until = time.time() + args.duration
        stack.event("soak-start", duration=args.duration, echo_workers=args.echo_workers,
                    echo_rate=args.echo_rate, mcp_workers=args.mcp_workers, mcp_rate=args.mcp_rate)
        workers = [Worker(stack, rec, "echo", "a", "a", f"e{i}") for i in range(args.echo_workers)]
        workers += [Worker(stack, rec, "mcp", "a", "a", f"m{i}") for i in range(args.mcp_workers)]

        async def progress():
            while time.time() < until:
                await asyncio.sleep(max(0.0, min(300.0, until - time.time())))
                sessions, rotations, _ = stack.device_sessions("a")
                stack.event("progress", requests=rec.count, sessions=len(sessions),
                            rotations=rotations, relay_alive=stack.relay.poll() is None,
                            device_alive=stack.devices["a"]["proc"].poll() is None)

        tasks = [w.loop_rate(args.echo_rate if w.kind == "echo" else args.mcp_rate, until)
                 for w in workers]
        await asyncio.gather(progress(), *tasks)
        for w in workers:
            await w.shutdown()
        sessions, rotations, _ = stack.device_sessions("a")
        mcp_ok = sum(w.mcp_calls_ok for w in workers)
        invocations = (stack.devices["a"]["dir"] / "mcp-workspace" / "invocations.log")
        backend_calls = invocations.read_text().count("echo\n") if invocations.exists() else None
        stack.event("soak-end", sessions=len(sessions), rotations=rotations)
    finally:
        if sampler:
            sampler.stop()
        rec.close()
        stack.close()
    run_rows = [r for r in rec.rows if r[3] == "run"]
    write_summary(run_dir, {
        "experiment": "soak", "nonce": nonce, "head": head_sha(), "duration_s": args.duration,
        "device_sessions": sessions, "rotations_completed": rotations,
        "echo": summarize_rows(run_rows, "echo"), "mcp": summarize_rows(run_rows, "mcp"),
        "mcp_tool_calls_ok_seen_by_consumer": mcp_ok,
        "mcp_backend_invocations_including_warmup": backend_calls,
        "processes": summarize_samples(run_dir / "samples.csv"),
    })


async def load(args: argparse.Namespace) -> None:
    run_dir, nonce = make_run(args, "load")
    stack = base_stack(args, run_dir, nonce, "m6-03-load")
    rec = Recorder(run_dir / "requests.csv", nonce)
    steps = [int(s) for s in args.steps.split(",")]
    results = []
    sampler = None
    try:
        stack.start_relay()
        stack.start_device("a")
        sampler = Sampler(stack, interval=5, fd_every=2)
        sampler.start()
        await wait_serving(stack, rec)
        await wait_serving(stack, rec, kind="mcp")
        for kind in args.kinds.split(","):
            for concurrency in steps:
                rec.phase = f"{kind}-c{concurrency}"
                stack.event("load-step", kind=kind, concurrency=concurrency, seconds=args.step_seconds)
                # MCP workers share at most --mcp-sessions sessions (M6-C146).
                pool = (McpSessionPool(min(concurrency, args.mcp_sessions))
                        if kind == "mcp" else None)
                # M6-C182: `--generator-processes N` runs an echo step's
                # workers in N `client` subprocesses instead of on this loop.
                off_loop = kind == "echo" and args.generator_processes > 0
                workers = [] if off_loop else [
                    Worker(stack, rec, kind, "a", "a", f"{kind}{concurrency}-{i}",
                           payload_size=args.payload, mcp_pool=pool, mcp_slot=i)
                    for i in range(concurrency)]
                for w in workers:
                    w.honor_retry_after = args.honor_retry_after
                until = time.time() + args.step_seconds
                lag = LoopLag()
                cpu_before = cpu_snapshot(stack)
                clients = (await start_clients(stack, rec, "a", "a", f"{kind}{concurrency}",
                                               concurrency, args.generator_processes, until,
                                               payload=args.payload,
                                               honor_retry_after=args.honor_retry_after)
                           if off_loop else asyncio.sleep(0, {}))
                gathered = await asyncio.gather(clients, lag.run(until),
                                                *(w.loop_closed(until) for w in workers))
                attribution = {"generator_processes": args.generator_processes if off_loop else 0,
                               "honor_retry_after": args.honor_retry_after,
                               "driver_loop_lag_ms": lag.summary(),
                               "cpu_percent": cpu_percent(cpu_before, cpu_snapshot(stack)),
                               "off_loop_clients": gathered[0].get("processes", [])}
                if pool is not None:
                    # Release the step's connections first, then DELETE on a
                    # fresh one, so a listener connection limit or a reset
                    # keep-alive does not strand a session (M6-C146).
                    for w in workers:
                        await w.conn.close()
                    await pool.close(workers[0])
                    report_mcp_pool(stack, pool, rec.phase)
                for w in workers:
                    await w.shutdown()
                s = summarize_rows(rec.rows, kind, rec.phase)
                s.update({"kind": kind, "concurrency": concurrency, **attribution})
                if pool is not None:
                    s["mcp_sessions"] = pool.stats()
                results.append(s)
                stack.event("load-step-done", kind=kind, concurrency=concurrency,
                            ok_per_s=s["throughput_ok_per_s"], p99=s["latency_ms_ok"]["p99"],
                            cpu_percent=s["cpu_percent"], driver_loop_lag_ms=s["driver_loop_lag_ms"],
                            errors=s["errors_by_code"], mcp_sessions=s.get("mcp_sessions"))
                await asyncio.sleep(3)
    finally:
        if sampler:
            sampler.stop()
        rec.close()
        stack.close()
    first_refusal = next(({"kind": r["kind"], "concurrency": r["concurrency"],
                           "codes": r["errors_by_code"]} for r in results if r["errors"]), None)
    write_summary(run_dir, {"experiment": "load", "nonce": nonce, "head": head_sha(),
                            "steps": results, "first_refusal": first_refusal,
                            "processes": summarize_samples(run_dir / "samples.csv")})


async def fairness(args: argparse.Namespace) -> None:
    run_dir, nonce = make_run(args, "fairness")
    stack = base_stack(args, run_dir, nonce, "m6-03-fair", mcp=False)
    rec = Recorder(run_dir / "requests.csv", nonce)
    sampler = None
    attribution: dict[str, dict] = {}
    try:
        stack.add_user("b")
        stack.add_device("b", "b", {"echo": "echo"})
        # Variant: user b also granted on the flooder's device (a shared device).
        stack.grant("b", "a", "echo")
        stack.start_relay()
        stack.start_device("a")
        stack.start_device("b")
        sampler = Sampler(stack, interval=5, fd_every=2)
        sampler.start()
        await wait_serving(stack, rec, "a", "a")
        await wait_serving(stack, rec, "b", "b")
        phases = [("baseline", 0), ("flood", args.flood_workers), ("recovery", 0)]
        for target in ("b", "a"):  # b's own device, then the shared device a
            for phase, flood in phases:
                rec.phase = f"{phase}-quiet-on-{target}"
                stack.event("fairness-phase", phase=rec.phase, flood_workers=flood)
                until = time.time() + args.phase_seconds
                quiet = [Worker(stack, rec, "echo", "b", target, f"quiet-{target}-{phase}-{i}")
                         for i in range(args.quiet_workers)]
                # `--flood-processes N` moves A's flood off this loop into N
                # client processes (M6-C183).
                off_flood = flood > 0 and args.flood_processes > 0
                flooders = [] if off_flood else [
                    Worker(stack, rec, "echo", "a", "a", f"flood-{target}-{i}")
                    for i in range(flood)]
                for w in flooders:
                    w.honor_retry_after = args.honor_retry_after
                # M6-C183: the same quiet workload again, timed on its own
                # event loop in a separate process, beside the in-loop one.
                # Both of B's clients open their keep-alive connections before
                # the flood starts: a B that connects during the flood competes
                # with A for the listener's connection permits instead.
                for w in quiet:
                    await asyncio.wait_for(w.conn.ensure(), 30)
                off_loop = await start_clients(stack, rec, "b", target, f"offloop-{target}-{phase}",
                                               args.quiet_workers, 1, until, rate=args.quiet_rate,
                                               preconnect=True)
                flood_clients = (await start_clients(
                    stack, rec, "a", "a", f"flood-{target}", flood, args.flood_processes, until,
                    honor_retry_after=args.honor_retry_after)
                    if off_flood else asyncio.sleep(0, {}))
                lag = LoopLag()
                cpu_before = cpu_snapshot(stack)
                results = await asyncio.gather(
                    off_loop,
                    flood_clients,
                    lag.run(until),
                    *(w.loop_rate(args.quiet_rate, until) for w in quiet),
                    *(w.loop_closed(until) for w in flooders))
                attribution[rec.phase] = {"driver_loop_lag_ms": lag.summary(),
                                          "cpu_percent": cpu_percent(cpu_before, cpu_snapshot(stack)),
                                          "off_loop_clients": results[0]["processes"],
                                          "flood_processes": results[1].get("processes", [])}
                for w in quiet + flooders:
                    await w.shutdown()
                await asyncio.sleep(3)
    finally:
        if sampler:
            sampler.stop()
        rec.close()
        stack.close()
    report = {}
    for target in ("b", "a"):
        for phase, _ in phases:
            name = f"{phase}-quiet-on-{target}"
            quiet_rows = [r for r in rec.rows if r[3] == name and r[2].startswith("quiet")]
            off_rows = [r for r in rec.rows if r[3] == name and r[2].startswith("offloop")]
            flood_rows = [r for r in rec.rows if r[3] == name and r[2].startswith("flood")]
            report[name] = {"quiet_user_b": summarize_rows(quiet_rows),
                            "quiet_user_b_off_loop": summarize_rows(off_rows),
                            "flooding_user_a": summarize_rows(flood_rows),
                            **attribution.get(name, {})}
    write_summary(run_dir, {"experiment": "fairness", "nonce": nonce, "head": head_sha(),
                            "flood_workers": args.flood_workers, "quiet_workers": args.quiet_workers,
                            "quiet_rate_per_worker": args.quiet_rate,
                            "flood_processes": args.flood_processes,
                            "honor_retry_after": args.honor_retry_after, "phases": report,
                            "processes": summarize_samples(run_dir / "samples.csv")})


async def flood(args: argparse.Namespace) -> None:
    """Reproduction for M6-C120/M6-C121: one device, N closed-loop echo
    consumers for a fixed time; report every device session end and whether
    `connect` exited, and with what."""
    run_dir, nonce = make_run(args, "flood")
    stack = base_stack(args, run_dir, nonce, "m6-03-flood", mcp=False)
    rec = Recorder(run_dir / "requests.csv", nonce)
    try:
        stack.start_relay()
        stack.start_device("a")
        await wait_serving(stack, rec)
        rec.phase = f"flood-c{args.workers}"
        stack.event("flood-start", workers=args.workers, seconds=args.seconds)
        workers = [Worker(stack, rec, "echo", "a", "a", f"f{i}", payload_size=args.payload)
                   for i in range(args.workers)]
        until = time.time() + args.seconds
        await asyncio.gather(*(w.loop_closed(until) for w in workers))
        for w in workers:
            await w.shutdown()
        rec.phase = "after"
        await asyncio.sleep(5)
        probe = Worker(stack, rec, "echo", "a", "a", "after")
        for _ in range(10):
            await probe.once()
            await asyncio.sleep(0.5)
        await probe.shutdown()
        proc = stack.devices["a"]["proc"]
        exit_code = proc.poll()
        _, _, events = stack.device_sessions("a")
    finally:
        rec.close()
        stack.close()
    ends = [e["result"] for e in events if isinstance(e.get("result"), dict)
            and e["result"].get("state") == "disconnected"]
    terminal = [e["error"] for e in events if e.get("ok") is False and e.get("error")]
    write_summary(run_dir, {
        "experiment": "flood", "nonce": nonce, "head": head_sha(), "workers": args.workers,
        "seconds": args.seconds, "device_exit_code": exit_code,
        "device_session_ends": [{"code": e.get("code"), "message": e.get("message"),
                                 "ready_ms": e.get("ready_ms")} for e in ends],
        "device_terminal_errors": terminal,
        "flood": summarize_rows(rec.rows, "echo", f"flood-c{args.workers}"),
        "after": summarize_rows(rec.rows, "echo", "after"),
    })


class DedicatedRedis:
    """A throwaway Redis container this run owns; never the shared one."""

    def __init__(self, nonce: str):
        self.name = f"m6-03-soak-chaos-{nonce}"
        # Docker on this shared host can take minutes to start a container.
        run(timeout=600, args=["docker", "run", "-d", "--rm", "--name", self.name, "--label",
             f"m6-03-soak={nonce}", "-p", "127.0.0.1::6379", REDIS_IMAGE,
             "redis-server", "--appendonly", "yes", "--appendfsync", "always"])
        try:  # a container that never answers is removed, not left behind
            port = run(["docker", "port", self.name, "6379/tcp"]).stdout.decode().strip().splitlines()[0]
            self.port = int(port.rsplit(":", 1)[1])
            deadline = time.time() + 30
            while time.time() < deadline:
                try:
                    if b"PONG" in resp("127.0.0.1", self.port, ["PING"]):
                        return
                except OSError:
                    pass
                time.sleep(0.2)
            raise SystemExit("dedicated Redis did not answer PING")
        except BaseException:
            self.remove()
            raise

    def pause(self) -> None:
        run(["docker", "pause", self.name], timeout=300)

    def unpause(self) -> None:
        run(["docker", "unpause", self.name], timeout=300)

    def remove(self) -> None:
        run(["docker", "rm", "-f", self.name], check=False, timeout=600)


async def chaos(args: argparse.Namespace) -> None:
    run_dir, nonce = make_run(args, "chaos")
    # The Redis pause needs a container this run owns.  Without
    # --dedicated-redis (the default since Docker Desktop was unavailable on
    # 2026-09-26), every other fault runs against the shared Redis under a
    # unique namespace, and the pause is recorded as not run.
    redis = None
    stack = None
    rec = Recorder(run_dir / "requests.csv", nonce)
    faults = []
    sampler = None
    try:
        if args.dedicated_redis:
            redis = DedicatedRedis(nonce)
        if redis:
            stack = base_stack(args, run_dir, nonce, "m6-03-chaos",
                               redis=("127.0.0.1", redis.port),
                               relay_extra="redis_restart_continuity_seconds = 1\n")
            stack.event("dedicated-redis", container=redis.name, port=redis.port)
        else:
            stack = base_stack(args, run_dir, nonce, "m6-03-chaos")
            stack.event("shared-redis", redis=args.redis)
        stack.start_relay()
        stack.start_device("a")
        sampler = Sampler(stack, interval=5, fd_every=2)
        sampler.start()
        await wait_serving(stack, rec)
        await wait_serving(stack, rec, kind="mcp")
        stop = asyncio.Event()
        probes = [Worker(stack, rec, "echo", "a", "a", f"probe-e{i}") for i in range(4)]
        probes += [Worker(stack, rec, "mcp", "a", "a", f"probe-m{i}") for i in range(2)]

        async def probe(w: Worker):
            while not stop.is_set():
                await w.once()
                await asyncio.sleep(0.1)

        tasks = [asyncio.create_task(probe(w)) for w in probes]

        async def settle(label: str, seconds: float = 20):
            rec.phase = f"steady-before-{label}"
            await asyncio.sleep(seconds)

        async def measure_recovery(label: str, fault_t: float, limit: float = 180) -> float | None:
            """Seconds from fault_t to the first echo 200 whose request STARTED after fault_t
            and after the fault ended; None if not within limit."""
            deadline = time.time() + limit
            while time.time() < deadline:
                ok = [r for r in rec.rows if r[3] == label and r[1] == "echo" and r[8] == 1
                      and r[0] >= fault_t]
                if ok:
                    return round(ok[0][0] + ok[0][4] / 1000 - fault_t, 3)
                await asyncio.sleep(0.2)
            return None

        dev = stack.devices["a"]

        async def device_fault(label: str, sig: int, restart_after: float):
            await settle(label)
            rec.phase = label
            t = time.time()
            stack.event("fault", fault=label, signal=sig)
            dev["proc"].send_signal(sig)
            try:
                code = await asyncio.to_thread(dev["proc"].wait, 30)
            except subprocess.TimeoutExpired:
                code = "no-exit-within-30s; SIGKILLed"
                stop_group(dev["proc"], timeout=0)
            exited = time.time()
            await asyncio.sleep(restart_after)
            restarted = time.time()
            stack.start_device("a")
            rec_s = await measure_recovery(label, restarted)
            faults.append({"fault": label, "device_exit": code,
                           "exit_after_s": round(exited - t, 3),
                           "restart_delay_s": restart_after,
                           "recovery_after_restart_s": rec_s})

        async def stop_fault(label: str, seconds: float):
            await settle(label)
            rec.phase = label
            t = time.time()
            stack.event("fault", fault=label, sigstop_seconds=seconds)
            dev["proc"].send_signal(signal.SIGSTOP)
            await asyncio.sleep(seconds)
            dev["proc"].send_signal(signal.SIGCONT)
            resumed = time.time()
            rec_s = await measure_recovery(label, resumed)
            await asyncio.sleep(2)
            exited = dev["proc"].poll()
            faults.append({"fault": label, "stopped_s": seconds,
                           "recovery_after_sigcont_s": rec_s,
                           "device_process_exited": exited,
                           "sessions_so_far": len(stack.device_sessions("a")[0])})
            if exited is not None:
                stack.start_device("a")
                await measure_recovery(label, time.time())

        async def redis_fault(label: str, seconds: float):
            await settle(label)
            rec.phase = label
            t = time.time()
            stack.event("fault", fault=label, pause_seconds=seconds)
            redis.pause()
            await asyncio.sleep(seconds)
            redis.unpause()
            resumed = time.time()
            rec_s = await measure_recovery(label, resumed)
            faults.append({"fault": label, "paused_s": seconds, "recovery_after_unpause_s": rec_s,
                           "relay_alive": stack.relay.poll() is None,
                           "relay_exit": stack.relay.poll()})
            if stack.relay.poll() is not None:
                stack.start_relay()
                await measure_recovery(label, time.time())

        async def relay_fault(label: str):
            await settle(label)
            rec.phase = label
            t = time.time()
            stack.event("fault", fault=label)
            stack.relay.send_signal(signal.SIGKILL)
            await asyncio.to_thread(stack.relay.wait, 30)
            restart_s = stack.start_relay(True)  # main thread: see spawn()
            listening = time.time()
            rec_s = await measure_recovery(label, listening)
            faults.append({"fault": label, "relay_restart_to_listening_s": round(restart_s, 3),
                           "recovery_after_listening_s": rec_s,
                           "total_outage_s": round((time.time() if rec_s is None else listening + rec_s) - t, 3),
                           "device_alive": dev["proc"].poll() is None})

        await device_fault("device-sigkill", signal.SIGKILL, 1.0)
        await device_fault("device-sigterm", signal.SIGTERM, 1.0)
        for seconds in (10, 40, 70):
            await stop_fault(f"device-sigstop-{seconds}s", seconds)
        if redis:
            await redis_fault("redis-pause-5s", 5)
        else:
            faults.append({"fault": "redis-pause-5s",
                           "not_run": "Docker unavailable (no dedicated container); "
                                      "the shared Redis is never paused"})
            stack.event("fault-not-run", fault="redis-pause-5s", reason="Docker unavailable")
        await relay_fault("relay-sigkill")
        await settle("end", 20)
        stop.set()
        await asyncio.gather(*tasks)
        for w in probes:
            await w.shutdown()
        mcp_ok = sum(w.mcp_calls_ok for w in probes)
        invocations = dev["dir"] / "mcp-workspace" / "invocations.log"
        backend = invocations.read_text().count("echo\n") if invocations.exists() else None
        sessions, rotations, _ = stack.device_sessions("a")
    finally:
        if sampler:
            sampler.stop()
        rec.close()
        if stack:
            stack.close()
        if redis:
            redis.remove()
    phases = sorted({r[3] for r in rec.rows})
    per_phase = {p: {"echo": summarize_rows(rec.rows, "echo", p),
                     "mcp": summarize_rows(rec.rows, "mcp", p)} for p in phases}
    mcp_unknown = sum(1 for r in rec.rows if r[1] == "mcp" and r[8] != 1
                      and r[7] not in ("not_dispatched",) and r[6] not in ("MCP_INIT_NO_SESSION",))
    write_summary(run_dir, {
        "experiment": "chaos", "nonce": nonce, "head": head_sha(), "faults": faults,
        "device_sessions": len(sessions), "rotations": rotations, "per_phase": per_phase,
        "integrity_mismatches": sum(1 for r in rec.rows if r[6] == "INTEGRITY_MISMATCH"),
        "mcp_tool_calls_ok_seen_by_consumer": mcp_ok,
        "mcp_backend_tool_invocations": backend,
        "mcp_non_ok_not_proven_undispatched": mcp_unknown,
        "processes": summarize_samples(run_dir / "samples.csv"),
    })


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    fwd = sub.add_parser("forwarder")
    fwd.add_argument("--cert", required=True)
    fwd.add_argument("--key", required=True)
    fwd.add_argument("--port", type=int, required=True)
    fwd.add_argument("--upstream", required=True)
    for name in ("soak", "load", "chaos", "fairness", "flood"):
        p = sub.add_parser(name)
        p.add_argument("--bin-dir", required=True)
        p.add_argument("--logs", required=True)
        p.add_argument("--redis", default="127.0.0.1:63790")
        p.add_argument("--max-load", type=float, default=20.0,
                       help="wait until the 1-minute load average is below this before starting")
        p.add_argument("--bin-head", default="unrecorded",
                       help="the commit the binaries in --bin-dir were built from")
        if name == "soak":
            p.add_argument("--duration", type=float, default=7200)
            p.add_argument("--echo-workers", type=int, default=4)
            p.add_argument("--echo-rate", type=float, default=2.5)
            p.add_argument("--mcp-workers", type=int, default=2)
            p.add_argument("--mcp-rate", type=float, default=1.0)
            p.add_argument("--sample-interval", type=float, default=15)
        if name == "load":
            p.add_argument("--steps", default="1,2,4,8,16,32,48,64,96,128")
            p.add_argument("--step-seconds", type=float, default=30)
            p.add_argument("--kinds", default="echo,mcp")
            p.add_argument("--payload", type=int, default=1024)
            p.add_argument("--generator-processes", type=int, default=0,
                           help="run each echo step's workers in this many separate client "
                                "processes, each with its own event loop (M6-C182); 0 keeps "
                                "them on the driver's loop.  MCP steps always run on the loop")
            p.add_argument("--honor-retry-after", action="store_true",
                           help="a worker refused CONNECTION_LIMIT waits the refusal's "
                                "retry_after_ms before its next request (M6-C182); by default "
                                "it retries at once")
            p.add_argument("--mcp-sessions", type=int, default=8,
                           help="MCP sessions shared by a step's workers (the stdio export's "
                                "default max_children is 8); every session is DELETEd after "
                                "the step")
        if name == "flood":
            p.add_argument("--workers", type=int, default=128)
            p.add_argument("--seconds", type=float, default=60)
            p.add_argument("--payload", type=int, default=1024)
        if name == "chaos":
            p.add_argument("--dedicated-redis", action="store_true",
                           help="start a throwaway Redis container and include the pause fault")
        if name == "fairness":
            p.add_argument("--flood-workers", type=int, default=128)
            p.add_argument("--quiet-workers", type=int, default=2)
            p.add_argument("--quiet-rate", type=float, default=5)
            p.add_argument("--phase-seconds", type=float, default=60)
            p.add_argument("--flood-processes", type=int, default=0,
                           help="run user A's flood in this many separate client processes "
                                "(M6-C183); 0 keeps it on the driver's loop")
            p.add_argument("--honor-retry-after", action="store_true",
                           help="flood workers refused CONNECTION_LIMIT wait its retry_after_ms")
    sub.add_parser("client", help="internal: echo workers on their own event loop; "
                                  "configuration on stdin")
    args = parser.parse_args()
    if args.cmd == "client":
        client_main()
        return
    if args.cmd == "forwarder":
        forwarder_main(args)
        return
    # SIGTERM/SIGHUP unwind through every `finally`, so children are stopped
    # and the namespace (and a chaos run's container) removed.
    def _unwind(signum, _frame):
        raise SystemExit(f"stopped by signal {signum}")
    signal.signal(signal.SIGTERM, _unwind)
    signal.signal(signal.SIGHUP, _unwind)
    asyncio.run({"soak": soak, "load": load, "chaos": chaos, "fairness": fairness,
                 "flood": flood}[args.cmd](args))


if __name__ == "__main__":
    main()
